#1207683239

JCC = javac
JFLAGS = 

default: HostDiscovery.class 
#Main.class

HostDiscovery.class: HostDiscovery.java
	$(JCC) $(JFLAGS) HostDiscovery.java

#Main.class: Main.java
#	$(JCC) $(JFLAGS) Main.java

clean:
	$(RM) *.class
